export const LAYOUT_CONSTANTS = {
  LARGE_HEADER_HEIGHT: 80,
  SMALL_HEADER_HEIGHT: 60,
  LARGE_HOME_BANNER_HEIGHT: 500,
  LARGE_DETAIL_BANNER_HEIGHT: 600,
  SMALL_DETAIL_BANNER_HEIGHT: 300,
  MOBILE_WIDTH: 700,
};
